/* StreamEmber Trainer — MHud page adapter for the StreamEmber overlay.
 *
 * Loaded by mhud/trainer.html (generated by build.ps1 from MHud/integration/mhud/html/index.html) AFTER mhud.js and
 * BEFORE app.js, so MHud's own app.js runs unchanged:
 *   - game -> page: window.streamember messages { action, data } are re-dispatched as window 'message' events,
 *     exactly like FiveM's SendNUIMessage, so MH.on('mhud:...') handlers in app.js receive them;
 *   - page -> game: MH.post(name, data) is routed to window.streamember.post({ cb: name, data }).
 * Adds: mouse clicks on the classic menu, keys forwarded by the game (F5 menu), a performance panel and
 * latency acknowledgements for the world tag messages.
 */
(function () {
  'use strict';
  var bridge = window.streamember;
  var MH = window.MH;

  /* ---------------- MHud NUI bridge ---------------- */
  MH.isNui = !!bridge;
  MH.post = function (name, data) {
    if (bridge) bridge.post({ cb: name, data: data || {} });
    else if (MH.debug) console.log('[trainer] post', name, data);
    return Promise.resolve({ ok: true });
  };

  var stats = { tagMsgs: 0, domTotal: 0, domMax: 0, domCount: 0, lastAckAt: 0, msgs: 0 };

  function dispatch(msg) {
    stats.msgs++;
    if (msg.action !== 'mhud:nametags') {
      window.dispatchEvent(new MessageEvent('message', { data: msg }));
      return;
    }
    var t0 = performance.now();
    window.dispatchEvent(new MessageEvent('message', { data: msg }));
    var dt = performance.now() - t0;
    stats.tagMsgs++;
    stats.domTotal += dt;
    stats.domCount++;
    if (dt > stats.domMax) stats.domMax = dt;
    // Acknowledge a sample right after processing: the game measures the full round trip
    if (msg.seq && t0 - stats.lastAckAt >= 500) {
      stats.lastAckAt = t0;
      MH.post('ack', { seq: msg.seq });
    }
  }
  if (bridge) {
    bridge.on(function (msg) { if (msg && typeof msg === 'object') dispatch(msg); });
  }

  /* The script (re)started while the page was already loaded */
  MH.on('trainer:hello', function () { MH.post('ready', {}); });

  /* ---------------- Menu input ---------------- */
  // Keys read by the game while the menu is open (no UI focus needed), fed to MHud's MH.listNav
  MH.on('trainer:key', function (d) {
    document.dispatchEvent(new KeyboardEvent('keydown', { key: d.key, bubbles: true, cancelable: true }));
  });

  // MH.listNav activates items on mouse move but selects only with Enter; make real clicks select too.
  document.addEventListener('click', function (e) {
    if (!e.isTrusted) return;  // listNav itself calls item.click() after Enter
    var item = e.target.closest('#menu-host .mh-classic__item');
    if (!item || item.classList.contains('is-disabled')) return;
    if (e.target.closest('.mh-check')) e.preventDefault();  // the Enter handler toggles the checkbox
    document.dispatchEvent(new KeyboardEvent('keydown', { key: 'Enter', bubbles: true, cancelable: true }));
  }, true);

  /* ---------------- Performance panel ---------------- */
  var ROWS = [
    ['gameFps', 'Oyun FPS'], ['pageFps', 'Sayfa FPS'], ['tags', 'Etiket'],
    ['tagRate', 'Etiket mesajı/sn (giden · gelen)'], ['dom', 'DOM ms (ort · maks)'],
    ['rtt', 'Gidiş-dönüş gecikme'], ['cs', 'C# ms (etiket · tick)'], ['traffic', 'Mesaj/sn · KB/sn'],
    ['cfg', 'Mesafe · sınır · sıklık · adım'], ['spin', 'Kamera dönüşü']
  ];
  var panel = document.createElement('div');
  panel.className = 'mh-anchor mh-mr x-perf-anchor';
  panel.innerHTML = '<div class="mh-panel x-perf mh-hidden" id="x-perf">' +
    '<div class="x-perf__head"><span class="mh-kicker mh-kicker--accent">Performans</span><span class="mh-badge mh-num" id="x-perf-state">—</span></div>' +
    '<div class="x-perf__grid">' + ROWS.map(function (r) {
      return '<span class="x-perf__k">' + r[1] + '</span><b class="x-perf__v mh-num" data-k="' + r[0] + '">—</b>';
    }).join('') + '</div>' +
    '<div class="x-perf__note mh-hidden" id="x-perf-refs">Kırmızı nokta = oyunun aynı karede çizdiği referans. Etiketin alt ucu noktada durmalı; dönerken aradaki kayma gecikmedir.</div>' +
    '</div>';
  var hint = document.createElement('div');
  hint.className = 'mh-anchor mh-bc x-hint-anchor';
  hint.innerHTML = '<div class="x-hint"><span class="mh-badge">F5</span> Trainer <span class="mh-badge">F7</span> Overlay <span class="mh-badge">F8</span> Fare</div>';

  function mount() {
    var screen = document.getElementById('screen') || document.querySelector('.mh-screen') || document.body;
    screen.appendChild(panel);
    screen.appendChild(hint);
  }
  if (document.readyState === 'loading') document.addEventListener('DOMContentLoaded', mount); else mount();

  function set(key, text) {
    var el = panel.querySelector('[data-k="' + key + '"]');
    if (el) el.textContent = text;
  }

  // Page FPS (requestAnimationFrame) and per-second page statistics
  var frames = 0, last = performance.now(), page = { fps: 0, tagRate: 0, domAvg: 0, domMax: 0 };
  function frame(now) {
    frames++;
    if (now - last >= 1000) {
      var sec = (now - last) / 1000;
      page.fps = Math.round(frames / sec);
      page.tagRate = Math.round(stats.tagMsgs / sec);
      page.domAvg = stats.domCount ? stats.domTotal / stats.domCount : 0;
      page.domMax = stats.domMax;
      frames = 0; last = now;
      stats.tagMsgs = 0; stats.domTotal = 0; stats.domCount = 0; stats.domMax = 0;
      set('pageFps', String(page.fps));
      set('dom', page.domAvg.toFixed(2) + ' · ' + page.domMax.toFixed(2));
    }
    requestAnimationFrame(frame);
  }
  requestAnimationFrame(frame);

  MH.on('trainer:perf', function (p) {
    var box = document.getElementById('x-perf');
    box.classList.toggle('mh-hidden', !p.show);
    document.getElementById('x-perf-refs').classList.toggle('mh-hidden', !p.refs);
    if (!p.show) return;
    set('gameFps', p.gameFps.toFixed(1));
    set('tags', String(p.tags));
    set('tagRate', p.tagMsgs + ' · ' + page.tagRate);
    set('rtt', p.rttMs > 0 ? p.rttMs.toFixed(1) + ' ms · ' + p.rttFrames.toFixed(1) + ' kare' : '—');
    set('cs', p.collectMs.toFixed(2) + ' · ' + p.tickMs.toFixed(2));
    set('traffic', Math.round(p.msgs) + ' · ' + p.kbps.toFixed(1));
    set('cfg', p.radius + ' m · ' + p.max + ' · ' + (p.rate ? p.rate + ' Hz' : 'her kare') + ' · ' + p.distStep + ' m');
    set('spin', p.spin ? p.spin + '°/sn' : 'kapalı');
    var state = document.getElementById('x-perf-state');
    var good = p.gameFps >= 55 && page.fps >= 55;
    state.textContent = good ? 'akıcı' : (p.gameFps >= 40 ? 'orta' : 'zorlanıyor');
    state.className = 'mh-badge mh-num ' + (good ? 'mh-t-success' : (p.gameFps >= 40 ? 'mh-t-warn' : 'mh-t-danger'));
  });
})();
