/* StreamEmber Trainer — MHud page adapter for the StreamEmber overlay.
 *
 * Loaded by mhud/trainer.html (generated by build.ps1 from MHud/integration/mhud/html/index.html) AFTER mhud.js and
 * BEFORE app.js, so MHud's own app.js runs unchanged:
 *   - game -> page: window.streamember messages { action, data } are re-dispatched as window 'message' events,
 *     exactly like FiveM's SendNUIMessage, so MH.on('mhud:...') handlers in app.js receive them;
 *   - page -> game: MH.post(name, data) is routed to window.streamember.post({ cb: name, data }).
 * Adds: mouse clicks on the classic menu, keys forwarded by the game (F5 menu), a performance panel,
 * latency acknowledgements for HTML-positioned tags and the sprite ATLAS for frame-synchronous world tags:
 *   the browser view is taller than the screen; the area below the screen holds fixed slots. Each slot renders one
 *   MHud tag (content only). The game draws the slots at the right screen positions itself, every frame.
 */
(function () {
  'use strict';
  var bridge = window.streamember;
  var MH = window.MH;

  /* ---------------- MHud NUI bridge ---------------- */
  MH.isNui = !!bridge;
  MH.post = function (name, data) {
    if (bridge) bridge.post({ cb: name, data: data || {} });
    else if (MH.debug) console.log('[trainer] post', name, data);
    return Promise.resolve({ ok: true });
  };

  var stats = { tagMsgs: 0, domTotal: 0, domMax: 0, domCount: 0, lastAckAt: 0, msgs: 0 };

  function dispatch(msg) {
    stats.msgs++;
    if (msg.action !== 'mhud:nametags') {
      window.dispatchEvent(new MessageEvent('message', { data: msg }));
      return;
    }
    var t0 = performance.now();
    window.dispatchEvent(new MessageEvent('message', { data: msg }));
    var dt = performance.now() - t0;
    stats.tagMsgs++;
    stats.domTotal += dt;
    stats.domCount++;
    if (dt > stats.domMax) stats.domMax = dt;
    // Acknowledge a sample right after processing: the game measures the full round trip
    if (msg.seq && t0 - stats.lastAckAt >= 500) {
      stats.lastAckAt = t0;
      MH.post('ack', { seq: msg.seq });
    }
  }
  if (bridge) {
    bridge.on(function (msg) { if (msg && typeof msg === 'object') dispatch(msg); });
  }

  /* ---------------- Atlas (frame-synchronous world tags) ---------------- */
  var atlas = { layout: null, heightDev: 0, screenHeightDev: 0, host: null, slots: [], pending: [], ackScheduled: false };

  function zoom() { return parseFloat(document.documentElement.style.zoom) || 1; }
  // Visible screen height in device pixels. With an atlas the browser view is taller than the screen.
  function screenHeightDev() {
    return atlas.layout ? atlas.screenHeightDev : window.innerHeight;
  }

  // MHud scales the HUD with zoom = innerHeight / 1080; base it on the screen, not the (taller) view
  var scalers = [];
  MH.autoScale = function (opts) {
    opts = opts || {};
    var base = opts.base || 1080, user = opts.scale || 1, target = MH.$(opts.target) || document.documentElement;
    function apply() { target.style.zoom = (screenHeightDev() / base) * user; layoutAtlas(); }
    apply();
    window.addEventListener('resize', apply);
    var scaler = { set: function (v) { user = v; apply(); }, apply: apply };
    scalers.push(scaler);
    return scaler;
  };
  function rescale() { if (scalers.length) scalers.forEach(function (x) { x.apply(); }); else layoutAtlas(); }

  // Positions the HUD screen and every slot in CSS pixels (device pixels / zoom)
  function layoutAtlas() {
    var screen = document.getElementById('screen') || document.querySelector('.mh-screen');
    var z = zoom(), L = atlas.layout;
    if (screen) {
      screen.style.bottom = L ? 'auto' : '';
      screen.style.height = L ? (atlas.screenHeightDev / z) + 'px' : '';
    }
    if (!L || !atlas.host) return;
    var sw = L.slotWidth / z, sh = L.slotHeight / z;
    atlas.host.style.top = (atlas.screenHeightDev / z) + 'px';
    atlas.host.style.width = (L.columns * sw) + 'px';
    atlas.host.style.height = (L.rows * sh) + 'px';
    atlas.slots.forEach(function (slot, i) {
      slot.el.style.left = ((i % L.columns) * sw) + 'px';
      slot.el.style.top = (Math.floor(i / L.columns) * sh) + 'px';
      slot.el.style.width = sw + 'px';
      slot.el.style.height = sh + 'px';
    });
  }

  function resetAtlas(layout) {
    if (atlas.host) atlas.host.remove();
    atlas.host = null; atlas.slots = []; atlas.pending = [];
    atlas.layout = layout || null;
    atlas.screenHeightDev = layout ? layout.screenHeight : 0;
    if (layout) {
      atlas.host = document.createElement('div');
      atlas.host.className = 'x-atlas';
      for (var i = 0; i < layout.columns * layout.rows; i++) {
        var el = document.createElement('div');
        el.className = 'x-slot';
        atlas.host.appendChild(el);
        atlas.slots.push({ el: el, pool: null });
      }
      document.body.appendChild(atlas.host);
    }
    rescale();
  }

  // The page reports painted slot versions; the game only shows a slot once its content is in the frame.
  function scheduleReadyAck() {
    if (atlas.ackScheduled) return;
    atlas.ackScheduled = true;
    requestAnimationFrame(function () {
      requestAnimationFrame(function () {
        atlas.ackScheduled = false;
        var L = atlas.layout;
        // Until Chromium has actually resized the view, the atlas rows are not painted yet
        if (!L || window.innerHeight < L.screenHeight + L.rows * L.slotHeight) {
          if (L && atlas.pending.length) setTimeout(scheduleReadyAck, 50);
          return;
        }
        if (!atlas.pending.length) return;
        var pairs = atlas.pending; atlas.pending = [];
        MH.post('atlasReady', { s: pairs });
      });
    });
  }

  MH.on('trainer:atlas', function (d) {
    if (d.reset) resetAtlas(d.layout && d.layout.rows > 0 ? d.layout : null);
    var L = atlas.layout;
    if (!L) return;
    var z = zoom(), sw = L.slotWidth / z, sh = L.slotHeight / z;
    (d.set || []).forEach(function (e) {
      var slot = atlas.slots[e.slot];
      if (!slot) return;
      if (!slot.pool) slot.pool = MH.Nametags(slot.el);
      var t = e.item;
      // Same mapping as MHud's app.js 'mhud:nametags', anchored to the slot's bottom center at scale 1
      t.id = 0;
      t.x = sw / 2; t.y = sh - 2; t.scale = 1; t.alpha = 1;
      t.sub = t.dist + ' M';
      t.tone = t.tone || 'team1';
      t.sig = [t.name, t.icon, t.tone, t.health, t.armor, t.dead, t.dist, t.compact].join('|');
      slot.pool.update([t]);
      atlas.pending.push(e.slot, e.ver);
    });
    (d.clear || []).forEach(function (i) {
      var slot = atlas.slots[i];
      if (slot && slot.pool) slot.pool.update([]);
    });
    if (atlas.pending.length) scheduleReadyAck();
  });
  window.addEventListener('resize', function () { if (atlas.pending.length) scheduleReadyAck(); });

  /* The script (re)started while the page was already loaded */
  MH.on('trainer:hello', function () { MH.post('ready', {}); });

  /* ---------------- Menu input ---------------- */
  // Keys read by the game while the menu is open (no UI focus needed), fed to MHud's MH.listNav
  MH.on('trainer:key', function (d) {
    document.dispatchEvent(new KeyboardEvent('keydown', { key: d.key, bubbles: true, cancelable: true }));
  });

  // MH.listNav activates items on mouse move but selects only with Enter; make real clicks select too.
  document.addEventListener('click', function (e) {
    if (!e.isTrusted) return;  // listNav itself calls item.click() after Enter
    var item = e.target.closest('#menu-host .mh-classic__item');
    if (!item || item.classList.contains('is-disabled')) return;
    if (e.target.closest('.mh-check')) e.preventDefault();  // the Enter handler toggles the checkbox
    document.dispatchEvent(new KeyboardEvent('keydown', { key: 'Enter', bubbles: true, cancelable: true }));
  }, true);

  /* ---------------- Performance panel ---------------- */
  var ROWS = [
    ['gameFps', 'Oyun FPS'], ['pageFps', 'Sayfa FPS'], ['tags', 'Etiket'],
    ['tagRate', 'Etiket mesajı/sn (giden · gelen)'], ['dom', 'DOM ms (ort · maks)'],
    ['mode', 'Konumlandırma'], ['rtt', 'HTML gidiş-dönüş gecikme'], ['content', 'Atlas içerik güncelleme/sn · slot'],
    ['cs', 'C# ms (etiket · tick)'], ['traffic', 'Mesaj/sn · KB/sn'],
    ['cfg', 'Mesafe · sınır · sıklık · adım'], ['spin', 'Kamera dönüşü']
  ];
  var panel = document.createElement('div');
  panel.className = 'mh-anchor mh-mr x-perf-anchor';
  panel.innerHTML = '<div class="mh-panel x-perf mh-hidden" id="x-perf">' +
    '<div class="x-perf__head"><span class="mh-kicker mh-kicker--accent">Performans</span><span class="mh-badge mh-num" id="x-perf-state">—</span></div>' +
    '<div class="x-perf__grid">' + ROWS.map(function (r) {
      return '<span class="x-perf__k">' + r[1] + '</span><b class="x-perf__v mh-num" data-k="' + r[0] + '">—</b>';
    }).join('') + '</div>' +
    '<div class="x-perf__note mh-hidden" id="x-perf-refs">Kırmızı nokta = oyunun aynı karede çizdiği referans. Etiketin alt ucu noktada durmalı; dönerken aradaki kayma gecikmedir.</div>' +
    '</div>';
  var hint = document.createElement('div');
  hint.className = 'mh-anchor mh-bc x-hint-anchor';
  hint.innerHTML = '<div class="x-hint"><span class="mh-badge">F5</span> Trainer <span class="mh-badge">F7</span> Overlay <span class="mh-badge">F8</span> Fare</div>';

  function mount() {
    var screen = document.getElementById('screen') || document.querySelector('.mh-screen') || document.body;
    screen.appendChild(panel);
    screen.appendChild(hint);
  }
  if (document.readyState === 'loading') document.addEventListener('DOMContentLoaded', mount); else mount();

  function set(key, text) {
    var el = panel.querySelector('[data-k="' + key + '"]');
    if (el) el.textContent = text;
  }

  // Page FPS (requestAnimationFrame) and per-second page statistics
  var frames = 0, last = performance.now(), page = { fps: 0, tagRate: 0, domAvg: 0, domMax: 0 };
  function frame(now) {
    frames++;
    if (now - last >= 1000) {
      var sec = (now - last) / 1000;
      page.fps = Math.round(frames / sec);
      page.tagRate = Math.round(stats.tagMsgs / sec);
      page.domAvg = stats.domCount ? stats.domTotal / stats.domCount : 0;
      page.domMax = stats.domMax;
      frames = 0; last = now;
      stats.tagMsgs = 0; stats.domTotal = 0; stats.domCount = 0; stats.domMax = 0;
      set('pageFps', String(page.fps));
      set('dom', page.domAvg.toFixed(2) + ' · ' + page.domMax.toFixed(2));
    }
    requestAnimationFrame(frame);
  }
  requestAnimationFrame(frame);

  MH.on('trainer:perf', function (p) {
    var box = document.getElementById('x-perf');
    box.classList.toggle('mh-hidden', !p.show);
    document.getElementById('x-perf-refs').classList.toggle('mh-hidden', !p.refs);
    if (!p.show) return;
    set('gameFps', p.gameFps.toFixed(1));
    set('tags', String(p.tags));
    set('tagRate', p.tagMsgs + ' · ' + page.tagRate);
    set('mode', p.mode === 'atlas' ? 'atlas · gecikme ' + p.delay + ' · öngörü ' + p.predict : 'HTML');
    set('rtt', p.mode === 'html' && p.rttMs > 0 ? p.rttMs.toFixed(1) + ' ms · ' + p.rttFrames.toFixed(1) + ' kare' : '—');
    set('content', p.mode === 'atlas' ? p.contentUpdates + ' · ' + p.slots : '—');
    set('cs', p.collectMs.toFixed(2) + ' · ' + p.tickMs.toFixed(2));
    set('traffic', Math.round(p.msgs) + ' · ' + p.kbps.toFixed(1));
    set('cfg', p.radius + ' m · ' + p.max + ' · ' + (p.rate ? p.rate + ' Hz' : 'her kare') + ' · ' + p.distStep + ' m');
    set('spin', p.spin ? p.spin + '°/sn' : 'kapalı');
    var state = document.getElementById('x-perf-state');
    var good = p.gameFps >= 55 && page.fps >= 55;
    state.textContent = good ? 'akıcı' : (p.gameFps >= 40 ? 'orta' : 'zorlanıyor');
    state.className = 'mh-badge mh-num ' + (good ? 'mh-t-success' : (p.gameFps >= 40 ? 'mh-t-warn' : 'mh-t-danger'));
  });
})();
