# StreamEmber product version for the C++ targets (the C# projects use Directory.Build.props).
#   -DSE_VERSION=1.2.3 | 1.2.3-ci.4 | 1.2.3-dev   (build.ps1 / CI pass it; computed from VERSION + git history)
# se_add_version_resource(<target> "<file description>") embeds a VERSIONINFO resource, so Explorer > Properties >
# Details shows the product, file version and SemVer of every shipped binary.
set(SE_VERSION "0.0.0-dev" CACHE STRING "StreamEmber product version (SemVer)")

if(NOT SE_VERSION MATCHES "^([0-9]+)\\.([0-9]+)\\.([0-9]+)")
  message(FATAL_ERROR "SE_VERSION must start with <major>.<minor>.<patch> (got '${SE_VERSION}')")
endif()
set(SE_VER_MAJOR ${CMAKE_MATCH_1})
set(SE_VER_MINOR ${CMAKE_MATCH_2})
set(SE_VER_PATCH ${CMAKE_MATCH_3})
message(STATUS "StreamEmber Overlay version: ${SE_VERSION}")

set(_SE_VERSION_RC_TEMPLATE "${CMAKE_CURRENT_LIST_DIR}/version.rc.in")

function(se_add_version_resource target description)
  get_target_property(_type ${target} TYPE)
  get_target_property(_name ${target} OUTPUT_NAME)
  if(NOT _name)
    set(_name ${target})
  endif()
  get_target_property(_suffix ${target} SUFFIX)
  if(NOT _suffix)
    if(_type STREQUAL "EXECUTABLE")
      set(_suffix ".exe")
    else()
      set(_suffix ".dll")
    endif()
  endif()
  set(SE_FILE_DESCRIPTION "${description}")
  set(SE_ORIGINAL_FILENAME "${_name}${_suffix}")
  set(SE_INTERNAL_NAME "${_name}")
  if(_type STREQUAL "EXECUTABLE")
    set(SE_FILE_TYPE "VFT_APP")
  else()
    set(SE_FILE_TYPE "VFT_DLL")
  endif()
  set(_rc "${CMAKE_CURRENT_BINARY_DIR}/${target}.version.rc")
  configure_file("${_SE_VERSION_RC_TEMPLATE}" "${_rc}" @ONLY)
  target_sources(${target} PRIVATE "${_rc}")
endfunction()
